"""Persistent and bundled "stops at" matrices.

Live sampling of due trains (see
:meth:`IrishRailClient.async_get_station_stops_at_options`) is the only
authoritative source of "where do this station's services go?" — the RTPI API
exposes no static route directory. Two derived layers make that truth
available even when no services are currently due:

* **Per-install cache** (:class:`StopsMatrixStore`) — every successful live
  discovery, whether from the config flow's ``stops_at`` step or from ordinary
  coordinator polling while a filter is active, is merged into a versioned
  :class:`~homeassistant.helpers.storage.Store` file and refreshed
  opportunistically thereafter. This keeps the matrix current ("static, but
  routinely checked and updated") without any external pipeline.
* **Bundled seed** (``stops_matrix.seed.json``, generated by
  ``scripts/build_stops_matrix.py``) — bootstraps fresh installs so setup at
  quiet hours does not degrade straight to the full national station list.

Lookups prefer exact-direction buckets and never fall back across directions,
so an option list can never contain a station the selected direction does not
serve.
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any

from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

from .const import DOMAIN, STOPS_MATRIX_FILENAME, STOPS_MATRIX_SEED_FILENAME

_LOGGER = logging.getLogger(__name__)

STOPS_STORE_VERSION = 1

# Bucket holding stops observed without a usable direction value. Lookups for
# a specific direction never read this bucket; it exists so directionless
# entries ("All") still get persistence.
ALL_DIRECTIONS_KEY = "_all"

# Key under ``hass.data[DOMAIN]`` for the per-hass singleton store instance;
# config flows may run before any config entry is set up, so lazily creating
# through this shared handle avoids two instances racing on one storage key.
STOPS_STORE_INSTANCE = "stops_matrix_store"

# Matrix shape: {"stations": {code: {"updated": iso-datetime,
#                                     "directions": {key: [names]}}}}
StopsMatrix = dict[str, Any]


def normalize_direction_key(direction: str | None) -> str:
    """Return the matrix bucket key for a direction filter value."""
    return (direction or "").casefold() or ALL_DIRECTIONS_KEY


def lookup_in_matrix(
    matrix: StopsMatrix | None, station_code: str, direction: str | None
) -> list[str] | None:
    """Return the stops recorded for a station/direction, or ``None``.

    Defensive against malformed data at every level: anything other than the
    expected structure yields ``None`` rather than raising, so a corrupt
    cache or seed can never break configuration. Results are sorted
    case-insensitively for stable dropdown ordering.
    """
    if not isinstance(matrix, dict):
        return None
    stations = matrix.get("stations")
    if not isinstance(stations, dict):
        return None
    entry = stations.get(station_code)
    if not isinstance(entry, dict):
        return None
    directions = entry.get("directions")
    if not isinstance(directions, dict):
        return None
    stops = directions.get(normalize_direction_key(direction))
    if not isinstance(stops, list):
        return None
    # Case-insensitive dedupe with first-seen casing wins, mirroring the
    # API client's union convention.
    seen: dict[str, str] = {}
    for stop in stops:
        if isinstance(stop, str) and stop:
            seen.setdefault(stop.casefold(), stop)
    if not seen:
        return None
    return sorted(seen.values(), key=str.casefold)


class StopsMatrixStore:
    """Merge-and-persist helper for the per-install "stops at" matrix."""

    def __init__(self, hass: HomeAssistant) -> None:
        """Initialize the store backed by HA's JSON storage."""
        self._hass = hass
        self._store: Store[StopsMatrix] = Store(
            hass, STOPS_STORE_VERSION, f"{DOMAIN}.{STOPS_MATRIX_FILENAME}"
        )
        self._data: StopsMatrix | None = None
        # Serializes read-modify-write across concurrent writers (the
        # coordinator's live learning, the config flow's discovery and the
        # rebuild sweep all record through this store).
        self._record_lock = asyncio.Lock()

    async def _async_ensure_loaded(self) -> StopsMatrix:
        """Load the stored matrix once; tolerate missing or corrupt files."""
        if self._data is None:
            try:
                loaded = await self._store.async_load()
            except (OSError, ValueError) as err:
                # A corrupted storage file must never break configuration;
                # treat it like an absent one and start learning afresh.
                _LOGGER.warning(
                    "Could not load stored stops matrix, starting empty: %s", err
                )
                loaded = None
            self._data = loaded if isinstance(loaded, dict) else {}
        return self._data

    async def async_lookup(
        self, station_code: str, direction: str | None
    ) -> list[str] | None:
        """Return cached stops for a station/direction, or ``None``."""
        data = await self._async_ensure_loaded()
        return lookup_in_matrix(data, station_code, direction)

    async def async_record(
        self, station_code: str, direction: str | None, stops: list[str]
    ) -> bool:
        """Merge observed stops into the matrix, saving only real changes.

        Returns ``True`` when the stored matrix changed. Steady-state polling
        re-observes the same stops, so the set comparison keeps converged
        installations from writing on every poll. Concurrent callers are
        serialized on the record lock so each merge observes the previous
        merge's result and each save carries it.
        """
        if not stops:
            return False
        async with self._record_lock:
            data = await self._async_ensure_loaded()
            stations: dict[str, Any] = data.setdefault("stations", {})
            entry: dict[str, Any] = stations.setdefault(station_code, {})
            directions: dict[str, Any] = entry.setdefault("directions", {})
            key = normalize_direction_key(direction)

            existing_raw = directions.get(key)
            existing = (
                {stop for stop in existing_raw if isinstance(stop, str) and stop}
                if isinstance(existing_raw, list)
                else set()
            )
            merged = existing | {stop for stop in stops if stop}
            if merged == existing:
                return False

            directions[key] = sorted(merged, key=str.casefold)
            entry["updated"] = dt_util.utcnow().isoformat()
            await self._store.async_save(data)
            return True


@callback
def get_stops_store(hass: HomeAssistant) -> StopsMatrixStore:
    """Return the per-hass stops-matrix singleton, creating it on demand."""
    domain_data = hass.data.setdefault(DOMAIN, {})
    store = domain_data.get(STOPS_STORE_INSTANCE)
    if not isinstance(store, StopsMatrixStore):
        store = StopsMatrixStore(hass)
        domain_data[STOPS_STORE_INSTANCE] = store
    return store


_SEED_CACHE: StopsMatrix | None = None
_SEED_CACHE_LOCK: asyncio.Lock | None = None


def _get_seed_cache_lock() -> asyncio.Lock:
    """Return the per-process lock guarding the seed cache.

    Created lazily so the lock is only allocated on first use; a
    top-level instantiation would allocate the object at import time
    even for callers that never touch the bundled seed. On Python
    3.10+ ``asyncio.Lock()`` does not require a running loop to
    construct, so the lazy pattern here is a deliberate
    pay-for-what-you-use choice rather than a workaround.
    """
    global _SEED_CACHE_LOCK
    if _SEED_CACHE_LOCK is None:
        _SEED_CACHE_LOCK = asyncio.Lock()
    return _SEED_CACHE_LOCK


def _read_bundled_matrix() -> StopsMatrix:
    """Read and validate the bundled seed matrix (blocking; run in executor).

    The seed lives at a fixed name inside the integration folder
    (``stops_matrix.seed.json``) so HACS updates refresh it from
    upstream while the per-install learned matrix (the storage file
    the rebuild button and live learning both write to) lives in
    HA's ``.storage/`` and is never clobbered by HACS.
    """
    path = Path(__file__).parent / STOPS_MATRIX_SEED_FILENAME
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise TypeError(f"{path.name} must contain a JSON object")
    return raw


async def async_load_bundled_stops_matrix() -> StopsMatrix:
    """Load the bundled seed matrix once, degrading to empty on failure.

    A missing, unreadable, or malformed seed must never block configuration;
    the failure is logged once and an empty matrix cached so subsequent
    lookups skip straight to later fallbacks.

    The check-then-set that populates ``_SEED_CACHE`` is guarded by an
    :class:`asyncio.Lock` so two coroutines that arrive while the
    cache is empty do not both read the file: the second arrival
    waits for the first to publish its result and returns the same
    object. The double-checked ``if _SEED_CACHE is None`` inside the
    critical section handles the case where the second arrival
    acquires the lock after the first has already populated the
    cache.
    """
    global _SEED_CACHE
    if _SEED_CACHE is None:
        async with _get_seed_cache_lock():
            if _SEED_CACHE is None:
                loop = asyncio.get_running_loop()
                try:
                    _SEED_CACHE = await loop.run_in_executor(
                        None, _read_bundled_matrix
                    )
                except (OSError, TypeError, ValueError) as err:
                    _LOGGER.warning(
                        "Could not load bundled stops matrix %s: %s",
                        STOPS_MATRIX_SEED_FILENAME,
                        err,
                    )
                    _SEED_CACHE = {}
    return _SEED_CACHE


@callback
def reset_bundled_seed_cache() -> None:
    """Forget the cached bundled seed so the next load re-reads the file.

    Called after the runtime rebuild button has finished so any
    improvements it made to the per-install matrix are reflected
    in the next config-flow lookup instead of being masked by a
    stale pre-rebuild seed cached in this process.
    """
    global _SEED_CACHE
    _SEED_CACHE = None
