"""Rebuild the bundled "stops at" seed matrix from the live RTPI API.

The Irish Rail RTPI API exposes no static route directory, so the seed is a
snapshot derived the same way the integration derives it at runtime: due
trains are sampled per station, each train code's movement history is scoped
to its current journey and cut downstream of the sampled station via
``IrishRailClient.scope_journey_stops``, and the resulting stops are stored
per direction bucket plus an ``_all`` union.

Run from the repository root inside the dev environment (requires the
integration's dependencies):

    python scripts/build_stops_matrix.py            # full rebuild
    python scripts/build_stops_matrix.py --limit 5  # smoke test

Because options come from services currently due, running the script at
different times of day (e.g. morning/evening peaks and midday) and merging
the outputs produces a fuller seed than any single run.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
from contextlib import suppress
from datetime import datetime
from pathlib import Path
from typing import Any

import aiohttp

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT))

from custom_components.irish_rail.pyirishrail import (
    IrishRailClient,
    IrishRailError,
    TrainMovement,
)
from custom_components.irish_rail.store import (
    ALL_DIRECTIONS_KEY,
    STOPS_STORE_VERSION,
    normalize_direction_key,
)

_LOGGER = logging.getLogger(__name__)

DEFAULT_OUTPUT = (
    _REPO_ROOT / "custom_components" / "irish_rail" / "stops_matrix.seed.json"
)


async def _train_movements(
    client: IrishRailClient,
    cache: dict[tuple[str, str], list[TrainMovement]],
    train_code: str,
    today: str,
) -> list[TrainMovement]:
    """Return the day's movements for a train code, tolerating failures."""
    key = (train_code, today)
    if key not in cache:
        try:
            cache[key] = await client.async_get_train_stops(train_code, date=today)
        except IrishRailError as err:
            _LOGGER.warning("Movement lookup failed for %s: %s", train_code, err)
            cache[key] = []
    return cache[key]


def _dump_document(output: Path, document: dict[str, Any]) -> None:
    """Write the seed document to a temp file, then atomically swap it in.

    The serialized JSON goes to a sibling temporary file first so an
    interrupted (mid-write) run never leaves a truncated seed; the real
    path is replaced only after that write fully succeeds. In either case
    the temporary file is removed afterwards.
    """
    temp_path = output.with_suffix(output.suffix + ".tmp")
    try:
        temp_path.write_text(
            json.dumps(document, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        os.replace(temp_path, output)
    finally:
        # Best-effort cleanup; the target path was already replaced or the
        # temp write failed, so no state is at risk here.
        with suppress(OSError):
            temp_path.unlink(missing_ok=True)


async def _build_matrix(
    delay: float, limit: int | None, output: Path
) -> dict[str, Any]:
    """Sample every station and assemble the seed document."""
    now_iso = datetime.now().astimezone().isoformat(timespec="seconds")
    document: dict[str, Any] = {
        "schema_version": STOPS_STORE_VERSION,
        "generated": now_iso,
        "note": (
            "Snapshot generated by scripts/build_stops_matrix.py from "
            "services due at generation time; refreshed opportunistically "
            "at runtime by the integration."
        ),
        "stations": {},
    }
    async with aiohttp.ClientSession(
        timeout=aiohttp.ClientTimeout(total=30)
    ) as session:
        client = IrishRailClient(session)
        stations = await client.async_get_all_stations()
        if limit is not None:
            stations = stations[:limit]
        today = datetime.now().astimezone().date().strftime("%d %b %Y")
        movement_cache: dict[tuple[str, str], list[TrainMovement]] = {}
        for index, station in enumerate(stations):
            try:
                trains = await client.async_get_station_by_code(station.code)
            except IrishRailError as err:
                _LOGGER.warning(
                    "Skipping %s (%s): %s", station.name, station.code, err
                )
                continue
            directions: dict[str, set[str]] = {}
            for train in trains:
                movements = await _train_movements(
                    client, movement_cache, train.code, today
                )
                journey = client.scope_journey_stops(
                    movements,
                    train.destination,
                    station_code=station.code,
                    station_name=station.name,
                )
                stops = {
                    movement.location for movement in journey if movement.location
                }
                stops.discard(station.name)
                if not stops:
                    continue
                key = normalize_direction_key(train.direction)
                directions.setdefault(key, set()).update(stops)
                directions.setdefault(ALL_DIRECTIONS_KEY, set()).update(stops)
            if directions:
                document["stations"][station.code] = {
                    "updated": now_iso,
                    "directions": {
                        key: sorted(stops, key=str.casefold)
                        for key, stops in sorted(directions.items())
                    },
                }
                summary = f"{len(directions)} direction bucket(s)"
            else:
                summary = "no services due"
            # Incremental dump after every station: an interrupted run still
            # leaves a valid, partial seed rather than nothing.
            await asyncio.to_thread(_dump_document, output, document)
            _LOGGER.info(
                "[%d/%d] %s (%s): %s",
                index + 1,
                len(stations),
                station.name,
                station.code,
                summary,
            )
            await asyncio.sleep(delay)
    return document


def main() -> None:
    """Parse arguments and run the sampler."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--delay",
        type=float,
        default=0.3,
        help="Seconds to sleep between stations (default: 0.3).",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Only sample the first N stations (smoke testing).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output JSON path (default: {DEFAULT_OUTPUT}).",
    )
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    document = asyncio.run(_build_matrix(args.delay, args.limit, args.output))
    # The loop already dumped incrementally after every sampled station, so
    # this only fires for the edge case of a zero-station run; route it
    # through the same atomic writer to avoid a duplicated raw dump.
    _dump_document(args.output, document)
    _LOGGER.info("Wrote %d stations to %s", len(document["stations"]), args.output)


if __name__ == "__main__":
    main()
